name = "MetatheoryPalomar433"
version = "0.1.0"
defaultTargets = ["Challenge", "Solution"]

[[require]]
name = "proofwidgets"
git = "https://github.com/leanprover-community/proofwidgets4"
rev = "4be2e3d5087eeb272cf5a8853b8f9dd025ef5957"

[[lean_lib]]
name = "PalomarCommon"
roots = ["PalomarCommon"]

[[lean_lib]]
name = "Challenge"
roots = ["Challenge"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]

[[lean_lib]]
name = "PalomarProof"
roots = ["PalomarProof"]
